name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: docker version
      run : docker --version
    - name: Build
      run: |
        cp .github/workflows/build.sh . && \
        chmod +x build.sh && \
        docker run \
        -v ${{ github.workspace }}:/build -v $PWD:/tmp --entrypoint "bash" \
        uofscphysics/root /tmp/build.sh
